# Generated by Django 3.0.4 on 2020-03-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last',
            new_name='last_name',
        ),
    ]
